namespace: game

imagesRegistry: xiancaige

core:
  version: latest
  port: 9999
  replicas: 1

gate:
  version: latest
  port: 30001
  replicas: 1
  
system:
  version: latest
  port: 20001
  replicas: 1

db:
  version: latest
  port: 18001
  replicas: 1
  
mongo:
  version: 4.0
  port: 27017
  replicas: 1
  hostname: tx
