namespace: game

imagesRegistry: xiancaige

core:
  ip: core-service
  version: latest
  port: 9999
  replicas: 1

gate:
  version: latest
  port: 30001
  replicas: 1
  
system:
  version: latest
  port: 20001
  replicas: 1
  ip: system-service
  battle_port_min: 31001
  battle_port_max: 32000
  game_player_num: 2
  battle_ip: 101.33.244.181
  
db:
  version: latest
  rpc_port: 18001
  replicas: 1
  
mongo:
  ip: mongo-service
  version: 4.0
  port: 27017
  replicas: 1
  hostname: tx3

  
battleMgr:
  accoutName: battle-mgr-ac
  battleImage: ue-ds
  battleVersion: ue5

battle:
  hostname: tx3
