
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: core
  ports:
  - name: tcp-9999
    protocol: TCP
    port: 9999
    targetPort: 9999