apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: core
  serviceName: core-service
  replicas: {{ .Values.core.replicas }}
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core 
        image: {{ .Values.imagesRegistry }}/core:{{ .Values.core.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.core.port }}
        env:
        - name: "PORT"
          value: "{{ .Values.core.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core
  ports:
  - name: tcp-{{ .Values.core.port }}
    protocol: TCP
    port: {{ .Values.core.port }}
    targetPort: {{ .Values.core.port }}