apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
  - name: tcp-18001
    protocol: TCP
    port: 18001
    targetPort: 18001