apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db 
        image: {{ .Values.imagesRegistry }}/db:{{ .Values.db.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.db.port }}