apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db-service
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db 
        image: {{ .Values.imagesRegistry }}/db:{{ .Values.db.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.db.rpc_port }}
        env:
        - name: "CORE.IP"
          value: "{{ .Values.core.ip }}"
        - name: "CORE.PORT"
          value: "{{ .Values.core.port }}"
        - name: "MONGO.IP"
          value: "{{ .Values.mongo.ip }}"
        - name: "MONGO.PORT"
          value: "{{ .Values.mongo.port }}"
        - name: "RPC.PORT"
          value: "{{ .Values.db.rpc_port }}"