apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db 
        image: xiancaige/db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 18001