apiVersion: v1
kind: Service
metadata:
  name: gate
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: gate
  ports:
  - name: tcp-19001
    protocol: TCP
    port: 19001
    targetPort: 19001