apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gate
  replicas: {{ .Values.gate.replicas }}
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - name: gate 
        image: {{ .Values.imagesRegistry }}/gate:{{ .Values.gate.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.gate.port }}
          