apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gate
  replicas: 1
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - name: gate 
        image: xiancaige/gate:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 19001