apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gate-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gate
  serviceName: gate-service  
  replicas: {{ .Values.gate.replicas }}
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - name: gate 
        image: {{ .Values.imagesRegistry }}/gate:{{ .Values.gate.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.gate.port }}
        env:
        - name: "CORE.IP"
          value: "{{ .Values.core.ip }}"
        - name: "CORE.PORT"
          value: "{{ .Values.core.port }}"
        - name: "PORT"
          value: "{{ .Values.gate.port }}"

---
apiVersion: v1
kind: Service
metadata:
  name: gate-service
spec:
  selector:
    app: gate
  ports:
  - name: tcp-{{ .Values.gate.port }}
    protocol: TCP
    port: {{ .Values.gate.port }}
    nodePort: {{ .Values.gate.port }}
  type: NodePort
