apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: mongo-workspace
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/mongo"
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.mongo.hostname }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: mongo-workspace
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service  
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo 
        image: mongo:{{ .Values.mongo.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.mongo.port }}
        volumeMounts:
        - name: pvc1
          mountPath: /data/db
      volumes:
      - name: pvc1
        persistentVolumeClaim:
          claimName: pvc-mongo 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - name: tcp-{{ .Values.mongo.port }}
    protocol: TCP
    port: {{ .Values.mongo.port }}
    targetPort: {{ .Values.mongo.port }}        
