apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: system
  replicas: {{ .Values.system.replicas }}
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system 
        image: {{ .Values.imagesRegistry }}/system:{{ .Values.system.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.system.port }}
        env:
        - name: "CORE.IP"
          value: "{{ .Values.core.ip }}"
        - name: "CORE.PORT"
          value: "{{ .Values.core.port }}"
        - name: "PORT"
          value: "{{ .Values.system.port }}"