apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: system
  replicas: 1
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system 
        image: xiancaige/system:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 20001