apiVersion: v1
kind: Service
metadata:
  name: system
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: system
  ports:
  - name: tcp-20001
    protocol: TCP
    port: 20001
    targetPort: 20001